### ISSUE TITLE
A Problem

### ISSUE THREAD

**Issue by Pepper2020** [alicehgsun/dialogflow-unity-v2#4]
Hi Alice and your teammates! Thank you for sharing such lucid tutorial videos. I'm a designer and I'm doing a project related to audio interaction based on Unity. I have followed your steps, but a problem showed up when I was adding the "NewScript" to the camera, which is an AR camera based on Vuforia. An error "400 Bad Request" was requested in the console. I have checked some answers on StackFlow, but most of those solutions look like javascript rather than CSharp. I wonder if you have ever met the same problem and probably you may share your solutions.

**Comment by koji** [comment]
@MariaLulu 
As you may know, `400 Bad Request` is caused by the client-side.
Mostly, using invalid endpoints(missing parameter or token info, etc) or cookies issue. 
I recommend you to check the endpoints you're using works on a web browser.

**Comment by Pepper2020** [comment]
Yes, you are right. It came out to be an error when I run the endpoints on a web browser. Then I tried the endpoint in the video and there was still an error. Do you guys know what may cause this problem? My terminal said "Your Google Cloud SDK is configured and ready to use!", I got the token and the project ID was copied from Dialogflow console. I'm confused...

**Comment by koji** [comment]
you can try the API with your cred.
https://cloud.google.com/dialogflow/docs/reference/rest/v2-overview
If you get an error, probably you may select a wrong role.
https://dialogflow.com/docs/reference/v2-auth-setup.

If your cred works properly, uniFlow itself has an issue like need more parameters which means you need to modify the codebase.

**Comment by Pepper2020** [comment]
Thank you for your patience. Now the error is 401 unauthorized... Do you have a clue?

**Comment by koji** [comment]
@MariaLulu you mean with Google api test tool or with unity?
anyways, 401 means your cred is something wrong.
you should follow this, https://dialogflow.com/docs/reference/v2-auth-setup

**Comment by Pepper2020** [comment]
It’s in Unity. Sorry to behave like an idiot!

**Comment by koji** [comment]
As I wrote, 401 is your cred's issue.
can you follow the above link and try your cred with google's api test tool?

the endpoints uniFlow uses are the followings.
https://github.com/ITP-xStory/uniFlow/blob/master/Assets/Plugins/DialogflowAPIScript.cs#L17

https://github.com/ITP-xStory/uniFlow/blob/master/Assets/Plugins/DialogflowAPIScript.cs#L66

**Comment by Pepper2020** [comment]
Thank you I will do!
